"""IBCS table-specific rule definitions."""
from __future__ import annotations
from typing import List
from ibcs_agent.rules.ibcs_rules import IBCSRule

# ---------------------------------------------------------------------------
# UN-UNIFY table rules
# ---------------------------------------------------------------------------
UN_TABLE_RULES: List[IBCSRule] = [
    # UN-T-01: Scenario abbreviations
    IBCSRule(
        id="UN-T-01.1",
        category="UNIFY",
        name="Falsches Szenario-Kuerzel AC",
        description="Spalte verwendet IST/Ist/Actual/ACT statt IBCS-Kuerzel AC",
        check_type="metadata",
        severity="error",
        violation_hint="Spaltenkopf enthaelt IST, Ist, Actual oder ACT statt AC",
        suggestion_template="Benenne Spalte in AC um gemaess IBCS-Notation",
        applies_to=['xlsx', 'pptx'],
    ),
    IBCSRule(
        id="UN-T-01.2",
        category="UNIFY",
        name="Falsches Szenario-Kuerzel PY",
        description="Spalte verwendet VJ/Vorjahr/Prior statt IBCS-Kuerzel PY",
        check_type="metadata",
        severity="error",
        violation_hint="Spaltenkopf enthaelt VJ, Vorjahr oder Prior statt PY",
        suggestion_template="Benenne Spalte in PY um gemaess IBCS-Notation",
        applies_to=['xlsx', 'pptx'],
    ),
    IBCSRule(
        id="UN-T-01.3",
        category="UNIFY",
        name="Falsches Szenario-Kuerzel PL",
        description="Spalte verwendet Budget/Bud statt IBCS-Kuerzel PL oder BU",
        check_type="metadata",
        severity="error",
        violation_hint="Spaltenkopf enthaelt Budget oder Bud statt PL oder BU",
        suggestion_template="Benenne Spalte in PL oder BU um gemaess IBCS-Notation",
        applies_to=['xlsx', 'pptx'],
    ),
    IBCSRule(
        id="UN-T-01.4",
        category="UNIFY",
        name="Falsches Szenario-Kuerzel FC",
        description="Spalte verwendet Forecast/HRE statt IBCS-Kuerzel FC",
        check_type="metadata",
        severity="error",
        violation_hint="Spaltenkopf enthaelt Forecast oder HRE statt FC",
        suggestion_template="Benenne Spalte in FC um gemaess IBCS-Notation",
        applies_to=['xlsx', 'pptx'],
    ),
    IBCSRule(
        id="UN-T-01.5",
        category="UNIFY",
        name="Nicht-IBCS-Szenario-Kuerzel",
        description="Unbekanntes Szenario-Kuerzel im Spaltenkopf gefunden",
        check_type="metadata",
        severity="warning",
        violation_hint="Spaltenkopf verwendet nicht IBCS-standardisiertes Kuerzel",
        suggestion_template="Verwende ausschliesslich AC/PY/PL/BU/FC als Szenario-Kuerzel",
        applies_to=['xlsx', 'pptx'],
    ),
    IBCSRule(
        id="UN-T-01.6",
        category="UNIFY",
        name="Kleinschreibung Szenario-Kuerzel",
        description="Szenario-Kuerzel muss vollstaendig grossgeschrieben sein",
        check_type="metadata",
        severity="warning",
        violation_hint="Kuerzel wie Ac, py, Pl statt AC/PY/PL verwendet",
        suggestion_template="Schreibe Szenario-Kuerzel vollstaendig gross: AC, PY, PL, FC",
        applies_to=['xlsx', 'pptx'],
    ),
    IBCSRule(
        id="UN-T-01.7",
        category="UNIFY",
        name="Gemischte Szenario-Notation",
        description="Unterschiedliche Schreibweisen desselben Szenarios in einer Datei",
        check_type="metadata",
        severity="error",
        violation_hint="AC und IST parallel fuer dasselbe Szenario verwendet",
        suggestion_template="Verwende konsequent nur eine IBCS-konforme Schreibweise",
        applies_to=['xlsx', 'pptx'],
    ),
    IBCSRule(
        id="UN-T-01.8",
        category="UNIFY",
        name="Fehlende Szenario-Spalten",
        description="Keine erkennbaren AC/PY/PL/FC-Spalten in der Tabelle",
        check_type="metadata",
        severity="warning",
        violation_hint="Tabelle hat keine IBCS-Szenario-Spalten",
        suggestion_template="Kennzeichne Szenarien mit IBCS-Kuerzeln im Spaltenkopf",
        applies_to=['xlsx', 'pptx'],
    ),
    IBCSRule(
        id="UN-T-01.9",
        category="UNIFY",
        name="Szenario-Kuerzel in Datenzellen",
        description="Szenario-Kuerzel erscheint in Datenzellen statt Spaltenkopf",
        check_type="metadata",
        severity="warning",
        violation_hint="Zellen enthalten Text wie IST oder AC neben Zahlen",
        suggestion_template="Platziere Szenario-Kuerzel nur im Spaltenkopf",
        applies_to=['xlsx', 'pptx'],
    ),
    # UN-T-02: Scenario visualization
    IBCSRule(
        id="UN-T-02.1",
        category="UNIFY",
        name="AC-Spalte nicht fett",
        description="AC-Werte muessen fett formatiert sein zur visuellen Unterscheidung",
        check_type="metadata",
        severity="error",
        violation_hint="AC-Spalte hat keine Fettformatierung",
        suggestion_template="Formatiere AC-Werte fett gemaess IBCS-Farbsemantik",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="UN-T-02.2",
        category="UNIFY",
        name="PY-Spalte nicht kursiv/grau",
        description="PY-Werte sollen kursiv oder grau dargestellt werden",
        check_type="metadata",
        severity="warning",
        violation_hint="PY-Spalte ist nicht kursiv oder grau formatiert",
        suggestion_template="Formatiere PY-Werte kursiv und/oder in Grauton gemaess IBCS",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="UN-T-02.3",
        category="UNIFY",
        name="PL-Spalte falsche Formatierung",
        description="PL-Werte sollen grau und nicht fett formatiert sein",
        check_type="metadata",
        severity="warning",
        violation_hint="PL-Spalte ist fett oder hat falsche Farbe",
        suggestion_template="Formatiere PL-Werte grau ohne Fettschrift gemaess IBCS",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="UN-T-02.4",
        category="UNIFY",
        name="FC-Spalte falsche Formatierung",
        description="FC-Werte sollen eine IBCS-konforme Kennzeichnung haben",
        check_type="metadata",
        severity="warning",
        violation_hint="FC-Spalte hat keine IBCS-konforme Formatierung",
        suggestion_template="Formatiere FC-Werte mit IBCS-konformer FC-Kennzeichnung",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="UN-T-02.5",
        category="UNIFY",
        name="Inkonsistente Szenario-Farben",
        description="Alle Spalten desselben Szenarios muessen dieselbe Formatierung haben",
        check_type="metadata",
        severity="error",
        violation_hint="Gleiche Szenario-Spalten haben unterschiedliche Formatierungen",
        suggestion_template="Vereinheitliche Formatierung aller AC/PY/PL-Spalten",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="UN-T-02.6",
        category="UNIFY",
        name="Bunte Hintergrundfarben ohne Semantik",
        description="Hintergrundfarben sollen semantisch bedeutsam sein, nicht dekorativ",
        check_type="metadata",
        severity="warning",
        violation_hint="Zellen haben bunte Hintergrundfarben ohne IBCS-Semantik",
        suggestion_template="Verwende Hintergrundfarben nur gemaess IBCS-Farbsemantik",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="UN-T-02.7",
        category="UNIFY",
        name="Fehlende visuelle Szenario-Unterscheidung",
        description="AC und PL muessen klar visuell unterscheidbar sein",
        check_type="metadata",
        severity="error",
        violation_hint="AC und PL-Spalten sehen identisch aus",
        suggestion_template="Unterscheide AC (fett/dunkel) und PL (grau/offen) visuell klar",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="UN-T-02.8",
        category="UNIFY",
        name="Abweichungsspalte ohne Farbformatierung",
        description="Abweichungsspalten benoetigen bedingte Formatierung fuer gruen/rot",
        check_type="metadata",
        severity="warning",
        violation_hint="Abweichungsspalte hat keine bedingte Farbformatierung",
        suggestion_template="Fuege bedingte Formatierung fuer pos/neg Abweichungen hinzu",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="UN-T-02.9",
        category="UNIFY",
        name="Inkonsistente Schriftstaerke",
        description="Schriftstaerke muss innerhalb desselben Szenarios konsistent sein",
        check_type="metadata",
        severity="warning",
        violation_hint="Manche AC-Zellen sind fett, andere nicht",
        suggestion_template="Setze Schriftstaerke konsistent pro Szenario-Typ",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="UN-T-02.10",
        category="UNIFY",
        name="Falsche Farbsemantik bei Abweichungen",
        description="Positive Abweichungen=gruen, negative=rot ist IBCS-Standard",
        check_type="metadata",
        severity="error",
        violation_hint="Negative Abweichungen sind gruen oder positive rot gefaerbt",
        suggestion_template="Korrigiere Farbsemantik: positiv=gruen, negativ=rot",
        applies_to=['xlsx'],
    ),
    # UN-T-03: Variance notation
    IBCSRule(
        id="UN-T-03.1",
        category="UNIFY",
        name="Fehlendes Delta-Symbol",
        description="Abweichungsspalten muessen das Delta-Zeichen verwenden",
        check_type="metadata",
        severity="error",
        violation_hint="Abweichungsspalte verwendet Abw, Delta oder Diff statt Delta-Zeichen",
        suggestion_template="Verwende Delta-Zeichen in Abweichungs-Spaltenkopf",
        applies_to=['xlsx', 'pptx'],
    ),
    IBCSRule(
        id="UN-T-03.2",
        category="UNIFY",
        name="Falsche Abweichungsrichtung",
        description="Notation muss DeltaAC-PL (AC minus PL) sein, nicht umgekehrt",
        check_type="metadata",
        severity="error",
        violation_hint="Abweichung als PL-AC statt AC-PL notiert",
        suggestion_template="Notiere Abweichung als DeltaAC-PL (Ist minus Plan)",
        applies_to=['xlsx', 'pptx'],
    ),
    IBCSRule(
        id="UN-T-03.3",
        category="UNIFY",
        name="Falsches Vorzeichen bei Kostenabweichung",
        description="Bei Kosten ist positiv=Mehraufwand, muss konsistent sein",
        check_type="metadata",
        severity="warning",
        violation_hint="Kostenabweichung hat falsches Vorzeichen-Konzept",
        suggestion_template="Definiere Vorzeichen-Konvention fuer Kosten-Abweichungen explizit",
        applies_to=['xlsx', 'pptx'],
    ),
    IBCSRule(
        id="UN-T-03.4",
        category="UNIFY",
        name="Absolute und relative Abweichung gemischt",
        description="Absolute und prozentuale Abweichungen sollen getrennte Spalten haben",
        check_type="metadata",
        severity="warning",
        violation_hint="Absolute und prozentuale Abweichung in einer Spalte gemischt",
        suggestion_template="Trenne DeltaAC-PL (absolut) und DeltaAC-PL in % in eigene Spalten",
        applies_to=['xlsx', 'pptx'],
    ),
    IBCSRule(
        id="UN-T-03.5",
        category="UNIFY",
        name="Fehlende relative Abweichungsspalte",
        description="Neben absoluter Abweichung soll auch eine prozentuale vorhanden sein",
        check_type="metadata",
        severity="info",
        violation_hint="Nur absolute Abweichung vorhanden, keine prozentuale",
        suggestion_template="Ergaenze Spalte fuer relative Abweichung (DeltaAC-PL in %)",
        applies_to=['xlsx', 'pptx'],
    ),
    IBCSRule(
        id="UN-T-03.6",
        category="UNIFY",
        name="Abweichung ohne Bezugsszenario",
        description="Abweichungsbezeichnung muss das Bezugsszenario enthalten",
        check_type="metadata",
        severity="error",
        violation_hint="Spalte heisst nur Delta ohne Angabe des Bezugsszenarios",
        suggestion_template="Benenne Abweichungsspalten mit Bezug: DeltaAC-PL, DeltaAC-PY",
        applies_to=['xlsx', 'pptx'],
    ),
    IBCSRule(
        id="UN-T-03.7",
        category="UNIFY",
        name="Prozent-Abweichung ohne Prozentzeichen",
        description="Prozentuale Abweichungsspalten muessen Prozentzeichen im Kopf haben",
        check_type="metadata",
        severity="error",
        violation_hint="Prozentuale Abweichungsspalte fehlt Prozentzeichen im Header",
        suggestion_template="Ergaenze Prozentzeichen im Spaltenkopf der relativen Abweichung",
        applies_to=['xlsx', 'pptx'],
    ),
    IBCSRule(
        id="UN-T-03.8",
        category="UNIFY",
        name="Falsche Abweichungs-Benennung",
        description="Abweichungsspalte verwendet falsche Bezeichnung statt Delta-Notation",
        check_type="metadata",
        severity="warning",
        violation_hint="Spalte heisst Differenz, Var oder Variance statt Delta-Notation",
        suggestion_template="Verwende Delta-Notation gemaess IBCS-Standard",
        applies_to=['xlsx', 'pptx'],
    ),
    IBCSRule(
        id="UN-T-03.9",
        category="UNIFY",
        name="Inkonsistente Abweichungsnotation",
        description="Alle Abweichungsspalten sollen dieselbe Notationskonvention verwenden",
        check_type="metadata",
        severity="warning",
        violation_hint="Manche Abweichungsspalten verwenden Delta, andere Abw",
        suggestion_template="Vereinheitliche alle Abweichungsbezeichnungen auf Delta-Notation",
        applies_to=['xlsx', 'pptx'],
    ),
    IBCSRule(
        id="UN-T-03.10",
        category="UNIFY",
        name="Abweichungsbalken ohne klare Skalierung",
        description="Skalierung von In-cell-Balken muss explizit und konsistent sein",
        check_type="metadata",
        severity="warning",
        violation_hint="Abweichungsbalken ohne klare Skalierung",
        suggestion_template="Setze explizite Skalierung fuer In-cell-Abweichungsbalken",
        applies_to=['xlsx', 'pptx'],
    ),
    # UN-T-04: Variance color coding
    IBCSRule(
        id="UN-T-04.1",
        category="UNIFY",
        name="Positive Abweichung nicht gruen",
        description="Positive Abweichungen muessen gruen gefaerbt sein",
        check_type="metadata",
        severity="error",
        violation_hint="Positive Abweichungen haben keine gruene Farbe",
        suggestion_template="Setze positive Abweichungen auf Gruen gemaess IBCS-Farbsemantik",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="UN-T-04.2",
        category="UNIFY",
        name="Negative Abweichung nicht rot",
        description="Negative Abweichungen muessen rot gefaerbt sein",
        check_type="metadata",
        severity="error",
        violation_hint="Negative Abweichungen haben keine rote Farbe",
        suggestion_template="Setze negative Abweichungen auf Rot gemaess IBCS-Farbsemantik",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="UN-T-04.3",
        category="UNIFY",
        name="Inkonsistente Abweichungsfarben",
        description="Abweichungsfarben muessen im gesamten Dokument konsistent sein",
        check_type="metadata",
        severity="error",
        violation_hint="Abweichungsfarben sind auf verschiedenen Sheets unterschiedlich",
        suggestion_template="Vereinheitliche Abweichungsfarben im gesamten Dokument",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="UN-T-04.4",
        category="UNIFY",
        name="Nur Farbe ohne Vorzeichen fuer Abweichungsrichtung",
        description="Vorzeichen und Farbe sollen beide die Richtung anzeigen",
        check_type="metadata",
        severity="warning",
        violation_hint="Abweichung nur durch Farbe unterschieden, kein Vorzeichen",
        suggestion_template="Verwende sowohl Vorzeichen als auch Farbe zur Abweichungsrichtung",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="UN-T-04.5",
        category="UNIFY",
        name="Gruen/Rot bei Nicht-Abweichungsspalten",
        description="Gruen und Rot sollen nur fuer Abweichungen verwendet werden",
        check_type="metadata",
        severity="warning",
        violation_hint="Gruen oder Rot in normalen Wert-Spalten ohne semantischen Grund",
        suggestion_template="Reserviere Gruen und Rot ausschliesslich fuer Abweichungsspalten",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="UN-T-04.6",
        category="UNIFY",
        name="Fehlende Farbkodierung in Abweichungsspalten",
        description="Abweichungsspalten ohne Farbformatierung sind schwer lesbar",
        check_type="metadata",
        severity="warning",
        violation_hint="Abweichungsspalten haben keine Farbkodierung",
        suggestion_template="Fuege bedingte Farbformatierung zu allen Abweichungsspalten hinzu",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="UN-T-04.7",
        category="UNIFY",
        name="Falsche Farbsemantik bei Kosten",
        description="Positive Kostenabweichung=mehr Kosten=schlecht=rot",
        check_type="metadata",
        severity="warning",
        violation_hint="Positive Kostenabweichung ist gruen statt rot markiert",
        suggestion_template="Beachte inverse Farbsemantik bei Kostenabweichungen",
        applies_to=['xlsx'],
    ),
    # UN-T-05: Unit placement
    IBCSRule(
        id="UN-T-05.1",
        category="UNIFY",
        name="Einheit in Datenzellen",
        description="Einheiten gehoeren in den Spaltenkopf, nicht in jede Zelle",
        check_type="metadata",
        severity="error",
        violation_hint="Datenzellen enthalten Einheitensymbol neben Zahlen",
        suggestion_template="Platziere Einheiten im Spaltenkopf, nicht in Datenzellen",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="UN-T-05.2",
        category="UNIFY",
        name="Nicht-ISO-Einheitenformat",
        description="Einheiten muessen ISO-konform sein: T€ oder Mio.€ statt TEUR",
        check_type="metadata",
        severity="warning",
        violation_hint="Einheit wird als TEUR, Mio EUR oder EUR Mio. angegeben",
        suggestion_template="Verwende ISO-Format: T€ fuer Tausend Euro, Mio.€ fuer Millionen",
        applies_to=['xlsx', 'pptx'],
    ),
    IBCSRule(
        id="UN-T-05.3",
        category="UNIFY",
        name="Fehlende Einheit im Spaltenkopf",
        description="Wert-Spaltenkoepfe muessen die Einheit enthalten",
        check_type="metadata",
        severity="error",
        violation_hint="Spaltenkopf hat keinen Einheitenhinweis fuer numerische Spalte",
        suggestion_template="Ergaenze Einheit im Spaltenkopf z.B. AC (T€)",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="UN-T-05.4",
        category="UNIFY",
        name="Inkonsistente Einheiten",
        description="Alle Wertspalten desselben Typs sollen dieselbe Einheit verwenden",
        check_type="metadata",
        severity="error",
        violation_hint="Manche Spalten in T€, andere in Mio.€ ohne klare Kennzeichnung",
        suggestion_template="Vereinheitliche Einheiten oder kennzeichne Unterschiede explizit",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="UN-T-05.5",
        category="UNIFY",
        name="Einheit im Titel fehlt",
        description="Tabellentitel soll Einheit enthalten falls nicht aus Header ersichtlich",
        check_type="metadata",
        severity="warning",
        violation_hint="Tabellentitel enthaelt keine Einheitsangabe",
        suggestion_template="Ergaenze Einheit im Tabellentitel oder Untertitel",
        applies_to=['xlsx', 'pptx'],
    ),
    IBCSRule(
        id="UN-T-05.6",
        category="UNIFY",
        name="Prozentzeichen in Absolutwert-Spalte",
        description="Prozentzeichen in Absolutwert-Spalten ist irrefuehrend",
        check_type="metadata",
        severity="error",
        violation_hint="Absolut-Wert-Spalte enthaelt Prozentzeichen im Kopf oder Format",
        suggestion_template="Entferne Prozentzeichen aus Absolutwert-Spalten",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="UN-T-05.7",
        category="UNIFY",
        name="Mehrere Einheiten in Spaltenkopf",
        description="Jeder Spaltenkopf soll nur eine Einheit enthalten",
        check_type="metadata",
        severity="warning",
        violation_hint="Spaltenkopf enthaelt mehrere Einheiten",
        suggestion_template="Trenne Spalten mit unterschiedlichen Einheiten",
        applies_to=['xlsx'],
    ),
    # UN-T-06: Time period notation
    IBCSRule(
        id="UN-T-06.1",
        category="UNIFY",
        name="Nicht-IBCS-Monatsabkuerzung",
        description="Monate muessen als Jan/Feb/Maer etc. abgekuerzt werden",
        check_type="metadata",
        severity="warning",
        violation_hint="Monate als January, Januar oder JAN geschrieben",
        suggestion_template="Verwende dreistellige Monatsabkuerzungen: Jan, Feb, Maer usw.",
        applies_to=['xlsx', 'pptx'],
    ),
    IBCSRule(
        id="UN-T-06.2",
        category="UNIFY",
        name="Falsche Quartal-Notation",
        description="Quartale muessen als Q1-Q4 bezeichnet werden",
        check_type="metadata",
        severity="warning",
        violation_hint="Quartal als 1.Q, Qrt1 oder I.Quartal angegeben",
        suggestion_template="Verwende Q1, Q2, Q3, Q4 als Quartal-Bezeichnung",
        applies_to=['xlsx', 'pptx'],
    ),
    IBCSRule(
        id="UN-T-06.3",
        category="UNIFY",
        name="Zweistellige Jahreszahl",
        description="Jahreszahlen muessen vierstellig sein (2024 nicht 24)",
        check_type="metadata",
        severity="error",
        violation_hint="Jahreszahl als zweistellige Zahl angegeben z.B. 24 statt 2024",
        suggestion_template="Verwende immer vierstellige Jahreszahlen",
        applies_to=['xlsx', 'pptx'],
    ),
    IBCSRule(
        id="UN-T-06.4",
        category="UNIFY",
        name="Fehlende YTD-Kennzeichnung",
        description="Kumulierte Jahreswerte muessen als YTD gekennzeichnet sein",
        check_type="metadata",
        severity="warning",
        violation_hint="Kumulierter Wert ohne YTD-Kennzeichnung",
        suggestion_template="Kennzeichne kumulierte Werte explizit als YTD",
        applies_to=['xlsx', 'pptx'],
    ),
    IBCSRule(
        id="UN-T-06.5",
        category="UNIFY",
        name="Inkonsistente Zeitperioden-Notation",
        description="Zeitperioden muessen in der gesamten Tabelle konsistent notiert sein",
        check_type="metadata",
        severity="warning",
        violation_hint="Manche Spalten Jan, andere Januar oder 01 als Monatsangabe",
        suggestion_template="Vereinheitliche Zeitperioden-Notation in der gesamten Tabelle",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="UN-T-06.6",
        category="UNIFY",
        name="Fehlende Zeitperiode in Kopfzeile",
        description="Spaltenkopf fuer Zeitperioden-Spalten muss den Zeitraum enthalten",
        check_type="metadata",
        severity="error",
        violation_hint="Zeitraums-Spalten haben keine Zeitangabe im Kopf",
        suggestion_template="Ergaenze Zeitperiode in Spaltenkopf z.B. Jan 2024, Q1 2024",
        applies_to=['xlsx', 'pptx'],
    ),
    # UN-T-07: Terminology consistency
    IBCSRule(
        id="UN-T-07.1",
        category="UNIFY",
        name="Inkonsistente Zeilenbeschriftungen",
        description="Gleichartige Positionen sollen in allen Tabellen identisch bezeichnet sein",
        check_type="metadata",
        severity="warning",
        violation_hint="Gleiche Position in verschiedenen Tabellen unterschiedlich benannt",
        suggestion_template="Erstelle und verwende ein einheitliches Bezeichnungs-Glossar",
        applies_to=['xlsx', 'pptx'],
    ),
    IBCSRule(
        id="UN-T-07.2",
        category="UNIFY",
        name="Abkuerzungen ohne Legende",
        description="Verwendete Abkuerzungen in Zeilentexten brauchen Erklaerung",
        check_type="metadata",
        severity="info",
        violation_hint="Tabelle enthaelt unbekannte Abkuerzungen ohne Erklaerung",
        suggestion_template="Ergaenze eine Legende oder erklaere Abkuerzungen in Fussnoten",
        applies_to=['xlsx', 'pptx'],
    ),
    IBCSRule(
        id="UN-T-07.3",
        category="UNIFY",
        name="Mischung Deutsch und Englisch",
        description="Tabellen sollen eine einheitliche Sprache verwenden",
        check_type="metadata",
        severity="warning",
        violation_hint="Tabelle enthaelt sowohl deutsche als auch englische Bezeichnungen",
        suggestion_template="Entscheide dich fuer eine Sprache und verwende sie konsequent",
        applies_to=['xlsx', 'pptx'],
    ),
]

# ---------------------------------------------------------------------------
# EX-EXPRESS table rules
# ---------------------------------------------------------------------------
EX_TABLE_RULES: List[IBCSRule] = [
    # EX-T-01: Table vs chart selection
    IBCSRule(
        id="EX-T-01.1",
        category="EXPRESS",
        name="Tabelle statt Chart fuer Zeitreihe",
        description="Zeitreihen mit vielen Perioden sind als Chart besser lesbar als Tabelle",
        check_type="metadata",
        severity="info",
        violation_hint="Tabelle zeigt mehr als 12 Zeitperioden ohne grafische Aufbereitung",
        suggestion_template="Erwage Chart-Darstellung fuer Zeitreihen mit vielen Datenpunkten",
        applies_to=['xlsx', 'pptx'],
    ),
    IBCSRule(
        id="EX-T-01.2",
        category="EXPRESS",
        name="Tabelle fuer Einzelwert-Vergleich geeignet",
        description="Tabellen eignen sich gut fuer genaue Wert-Ablese-Aufgaben",
        check_type="metadata",
        severity="info",
        violation_hint="Tabellenformat ist korrekt fuer praezisen Wertvergleich",
        suggestion_template="Tabelle ist gemaess IBCS fuer Einzelwert-Ablese-Aufgaben geeignet",
        applies_to=['xlsx', 'pptx'],
    ),
    IBCSRule(
        id="EX-T-01.3",
        category="EXPRESS",
        name="Fehlende Abweichungsspalten neben Werten",
        description="Plan/Ist-Vergleich braucht explizite Abweichungsspalten",
        check_type="metadata",
        severity="warning",
        violation_hint="Tabelle hat AC und PL aber keine Delta-Spalte",
        suggestion_template="Ergaenze Abweichungsspalte DeltaAC-PL neben Wertspalten",
        applies_to=['xlsx', 'pptx'],
    ),
    # EX-T-02: Column types
    IBCSRule(
        id="EX-T-02.1",
        category="EXPRESS",
        name="Fehlende Wertspalten",
        description="Tabelle braucht mindestens eine Absolutwert-Spalte",
        check_type="metadata",
        severity="error",
        violation_hint="Tabelle enthaelt keine numerischen Wertspalten",
        suggestion_template="Ergaenze Wertspalten fuer die relevanten Szenarien",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="EX-T-02.2",
        category="EXPRESS",
        name="Fehlende absolute Abweichungsspalte",
        description="Tabelle braucht eine Spalte fuer absolute Abweichung",
        check_type="metadata",
        severity="warning",
        violation_hint="Keine absolute Abweichungsspalte (DeltaAC-PL) vorhanden",
        suggestion_template="Ergaenze Spalte fuer absolute Abweichung DeltaAC-PL",
        applies_to=['xlsx', 'pptx'],
    ),
    IBCSRule(
        id="EX-T-02.3",
        category="EXPRESS",
        name="Fehlende relative Abweichungsspalte",
        description="Tabelle braucht eine Spalte fuer relative Abweichung in Prozent",
        check_type="metadata",
        severity="info",
        violation_hint="Keine relative Abweichungsspalte (%) vorhanden",
        suggestion_template="Ergaenze Spalte fuer relative Abweichung DeltaAC-PL in %",
        applies_to=['xlsx', 'pptx'],
    ),
    IBCSRule(
        id="EX-T-02.4",
        category="EXPRESS",
        name="In-cell-Balken falsch eingesetzt",
        description="In-cell-Balken sollen nur in Abweichungsspalten verwendet werden",
        check_type="metadata",
        severity="warning",
        violation_hint="In-cell-Balken in normalen Wertspalten statt Abweichungsspalten",
        suggestion_template="Verwende In-cell-Balken nur in Abweichungsspalten",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="EX-T-02.5",
        category="EXPRESS",
        name="Fehlende In-cell-Visualisierung",
        description="Abweichungsspalten sollen In-cell-Balken zur Visualisierung haben",
        check_type="metadata",
        severity="info",
        violation_hint="Abweichungsspalte ohne grafische In-cell-Darstellung",
        suggestion_template="Ergaenze In-cell-Balken (bedingte Formatierung) in Abweichungsspalten",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="EX-T-02.6",
        category="EXPRESS",
        name="Spaltentyp nicht erkennbar",
        description="Spaltentyp (Wert/abs. Abw./rel. Abw.) muss aus Header erkennbar sein",
        check_type="metadata",
        severity="warning",
        violation_hint="Spaltentyp ist aus dem Spaltenkopf nicht eindeutig erkennbar",
        suggestion_template="Kennzeichne Spaltentyp klar im Spaltenkopf",
        applies_to=['xlsx', 'pptx'],
    ),
    # EX-T-03: Template selection
    IBCSRule(
        id="EX-T-03.1",
        category="EXPRESS",
        name="IBCS T01-T04 Template nicht verwendet",
        description="IBCS definiert Tabellen-Templates T01 bis T04",
        check_type="metadata",
        severity="info",
        violation_hint="Keine erkennbare Verwendung eines IBCS-Tabellen-Templates",
        suggestion_template="Orientiere dich an IBCS-Templates T01 (einfach) bis T04 (vollstaendig)",
        applies_to=['xlsx', 'pptx'],
    ),
    IBCSRule(
        id="EX-T-03.2",
        category="EXPRESS",
        name="Falsches Template fuer Datentyp",
        description="Template-Wahl soll zum Dateninhalt passen",
        check_type="metadata",
        severity="info",
        violation_hint="Verwendetes Template scheint nicht optimal fuer die Datenstruktur",
        suggestion_template="Pruefe ob IBCS-Template besser zur Datenkomplexitaet passt",
        applies_to=['xlsx', 'pptx'],
    ),
    IBCSRule(
        id="EX-T-03.3",
        category="EXPRESS",
        name="Fehlende In-cell-Grafiken in Template",
        description="IBCS-Templates mit In-cell-Grafiken erhoehen Lesbarkeit",
        check_type="metadata",
        severity="info",
        violation_hint="Template ohne In-cell-Visualisierung trotz Abweichungsdaten",
        suggestion_template="Erwaege Template T03 oder T04 mit In-cell-Grafiken fuer Abweichungen",
        applies_to=['xlsx', 'pptx'],
    ),
    IBCSRule(
        id="EX-T-03.4",
        category="EXPRESS",
        name="Template-Konsistenz im Dokument",
        description="Alle aehnlichen Tabellen sollen dasselbe Template verwenden",
        check_type="metadata",
        severity="warning",
        violation_hint="Verschiedene Tabellen im Dokument verwenden unterschiedliche Templates",
        suggestion_template="Vereinheitliche Template-Wahl fuer alle vergleichbaren Tabellen",
        applies_to=['xlsx', 'pptx'],
    ),
    IBCSRule(
        id="EX-T-03.5",
        category="EXPRESS",
        name="Template ohne Abweichungsspalten",
        description="IBCS-Templates ab T02 enthalten immer Abweichungsspalten",
        check_type="metadata",
        severity="warning",
        violation_hint="Tabelle hat kein Template mit Abweichungsspalten obwohl Plan/Ist vorhanden",
        suggestion_template="Verwende Template T02+ mit Abweichungsspalten fuer Plan/Ist-Vergleiche",
        applies_to=['xlsx', 'pptx'],
    ),
    # EX-T-04: In-cell graphics
    IBCSRule(
        id="EX-T-04.1",
        category="EXPRESS",
        name="In-cell-Balken ohne explizite Skalierung",
        description="Skalierung von In-cell-Balken muss explizit definiert sein",
        check_type="metadata",
        severity="error",
        violation_hint="Datenbalken verwenden automatische Skalierung statt expliziter",
        suggestion_template="Setze explizite Min/Max-Werte fuer Datenbalken-Skalierung",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="EX-T-04.2",
        category="EXPRESS",
        name="Falsche In-cell-Balken-Farbe",
        description="In-cell-Balken fuer Abweichungen muessen gruen/rot kodiert sein",
        check_type="metadata",
        severity="warning",
        violation_hint="Datenbalken haben keine semantisch korrekte Farbe",
        suggestion_template="Verwende gruen fuer positive, rot fuer negative Abweichungsbalken",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="EX-T-04.3",
        category="EXPRESS",
        name="Fehlende Null-Achse in In-cell-Balken",
        description="Abweichungsbalken brauchen eine sichtbare Null-Achse",
        check_type="metadata",
        severity="warning",
        violation_hint="Datenbalken ohne erkennbare Null-Achse",
        suggestion_template="Stelle sicher dass die Null-Achse im Datenbalken sichtbar ist",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="EX-T-04.4",
        category="EXPRESS",
        name="Inkonsistente In-cell-Balken-Skalierung",
        description="Alle In-cell-Balken derselben Kategorie muessen gleich skaliert sein",
        check_type="metadata",
        severity="error",
        violation_hint="Datenbalken in verschiedenen Spalten haben unterschiedliche Skalierungen",
        suggestion_template="Vereinheitliche Skalierung aller In-cell-Balken derselben Kategorie",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="EX-T-04.5",
        category="EXPRESS",
        name="In-cell-Balken verdeckt Zahlenwert",
        description="Zahlenwert und Balken muessen gleichzeitig lesbar sein",
        check_type="metadata",
        severity="warning",
        violation_hint="In-cell-Balken ueberlappt mit Zahlenwert und macht ihn schwer lesbar",
        suggestion_template="Stelle sicher dass Zahlenwert trotz In-cell-Balken gut lesbar ist",
        applies_to=['xlsx'],
    ),
]

# ---------------------------------------------------------------------------
# CO-CONDENSE table rules
# ---------------------------------------------------------------------------
CO_TABLE_RULES: List[IBCSRule] = [
    # CO-T-01: One-page principle
    IBCSRule(
        id="CO-T-01.1",
        category="CONDENSE",
        name="Tabelle passt nicht auf eine Seite",
        description="IBCS-Tabellen sollen auf einer Seite darstellbar sein",
        check_type="metadata",
        severity="warning",
        violation_hint="Tabelle hat mehr Zeilen als auf einer Seite lesbar sind",
        suggestion_template="Verdichte Tabelle oder teile sie in separate thematische Tabellen",
        applies_to=['xlsx', 'pptx'],
    ),
    IBCSRule(
        id="CO-T-01.2",
        category="CONDENSE",
        name="Schriftgroesse unter 8pt",
        description="Mindestschriftgroesse fuer Tabellen ist 8pt",
        check_type="metadata",
        severity="error",
        violation_hint="Tabellenschriftgroesse ist kleiner als 8pt",
        suggestion_template="Erhoehe Schriftgroesse auf mindestens 8pt gemaess IBCS",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="CO-T-01.3",
        category="CONDENSE",
        name="Zu wenige Zeilen fuer Tabelle",
        description="Tabellen mit weniger als 3 Datenzeilen sind als Text besser darstellbar",
        check_type="metadata",
        severity="info",
        violation_hint="Tabelle hat sehr wenige Zeilen (unter 3 Datenzeilen)",
        suggestion_template="Erwaege Textdarstellung fuer sehr kleine Datenmenge",
        applies_to=['xlsx', 'pptx'],
    ),
    # CO-T-02: Row density
    IBCSRule(
        id="CO-T-02.1",
        category="CONDENSE",
        name="Ungleichmaessige Zeilenhoehen",
        description="Alle Datenzeilen sollen dieselbe Hoehe haben",
        check_type="metadata",
        severity="warning",
        violation_hint="Zeilenhoehen sind ungleichmaessig in der Tabelle",
        suggestion_template="Setze einheitliche Zeilenhoehe fuer alle Datenzeilen",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="CO-T-02.2",
        category="CONDENSE",
        name="Leerzeilen in Datentabelle",
        description="Leerzeilen verschwenden Platz und sollen vermieden werden",
        check_type="metadata",
        severity="warning",
        violation_hint="Tabelle enthaelt Leerzeilen zwischen Datenzeilen",
        suggestion_template="Entferne Leerzeilen aus der Datentabelle",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="CO-T-02.3",
        category="CONDENSE",
        name="Zu grosse Zeilenhoehe",
        description="Uebertrieben grosse Zeilenhoehe reduziert Informationsdichte",
        check_type="metadata",
        severity="info",
        violation_hint="Zeilenhoehe ist deutlich groesser als fuer Lesbarkeit noetig",
        suggestion_template="Reduziere Zeilenhoehe auf notwendiges Minimum",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="CO-T-02.4",
        category="CONDENSE",
        name="Fehlende Verdichtung bei aehnlichen Zeilen",
        description="Aehnliche Positionen koennen zu Gruppen zusammengefasst werden",
        check_type="metadata",
        severity="info",
        violation_hint="Tabelle hat viele Einzelzeilen die thematisch zusammengehoeren",
        suggestion_template="Gruppe verwandte Zeilen hierarchisch zur Verdichtung",
        applies_to=['xlsx', 'pptx'],
    ),
    # CO-T-03: Column widths
    IBCSRule(
        id="CO-T-03.1",
        category="CONDENSE",
        name="Ungleichmaessige Spaltenbreite gleicher Szenarios",
        description="Spalten desselben Szenario-Typs sollen gleich breit sein",
        check_type="metadata",
        severity="warning",
        violation_hint="AC-Spalten haben unterschiedliche Breiten",
        suggestion_template="Setze einheitliche Breite fuer Spalten desselben Szenario-Typs",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="CO-T-03.2",
        category="CONDENSE",
        name="Zu breite Wert-Spalten",
        description="Wert-Spalten sollen nur so breit sein wie noetig",
        check_type="metadata",
        severity="info",
        violation_hint="Wert-Spalten sind viel breiter als der Inhalt benoetigt",
        suggestion_template="Optimiere Spaltenbreiten fuer maximale Informationsdichte",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="CO-T-03.3",
        category="CONDENSE",
        name="Zu schmale Label-Spalte",
        description="Label-Spalte muss breit genug fuer vollstaendige Beschriftungen sein",
        check_type="metadata",
        severity="warning",
        violation_hint="Zeilenbeschriftungen werden abgeschnitten wegen zu schmaler Spalte",
        suggestion_template="Erbreite Label-Spalte um vollstaendige Beschriftungen anzuzeigen",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="CO-T-03.4",
        category="CONDENSE",
        name="Inkonsistente Spaltenbreiten",
        description="Spaltenbreiten sollen einem einheitlichen Raster folgen",
        check_type="metadata",
        severity="info",
        violation_hint="Spaltenbreiten sind uneinheitlich ohne erkennbares Raster",
        suggestion_template="Definiere ein Raster fuer Spaltenbreiten und wende es konsistent an",
        applies_to=['xlsx'],
    ),
    # CO-T-04: Value display
    IBCSRule(
        id="CO-T-04.1",
        category="CONDENSE",
        name="Fehlender Tausender-Trennzeichen",
        description="Zahlen ab 1000 sollen Tausender-Trennzeichen haben",
        check_type="metadata",
        severity="error",
        violation_hint="Zahlenwerte ohne Tausender-Trennzeichen in Wertspalten",
        suggestion_template="Aktiviere Tausender-Trennzeichen fuer alle Zahlenwerte",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="CO-T-04.2",
        category="CONDENSE",
        name="Nullwert als 0 statt Gedankenstrich",
        description="Nullwerte sollen als Gedankenstrich dargestellt werden, nicht als 0",
        check_type="metadata",
        severity="warning",
        violation_hint="Nullwerte werden als 0 angezeigt statt als Gedankenstrich",
        suggestion_template="Formatiere Nullwerte als Gedankenstrich gemaess IBCS-Konvention",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="CO-T-04.3",
        category="CONDENSE",
        name="Negative Zahlen nicht in Klammern",
        description="Negative Zahlen sollen in Klammern stehen nicht mit Minuszeichen",
        check_type="metadata",
        severity="warning",
        violation_hint="Negative Zahlen werden mit Minuszeichen statt Klammern angezeigt",
        suggestion_template="Formatiere negative Zahlen als (123) statt -123",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="CO-T-04.4",
        category="CONDENSE",
        name="Inkonsistente Dezimalstellen",
        description="Alle Zahlen einer Spalte sollen dieselbe Dezimalstellenanzahl haben",
        check_type="metadata",
        severity="error",
        violation_hint="Spalte hat Zahlen mit unterschiedlichen Dezimalstellen",
        suggestion_template="Setze einheitliche Dezimalstellenanzahl pro Spalte",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="CO-T-04.5",
        category="CONDENSE",
        name="Zu viele Dezimalstellen",
        description="Mehr als 1-2 Dezimalstellen sind in Tabellen meist unnoetig",
        check_type="metadata",
        severity="info",
        violation_hint="Zahlen haben mehr als 2 Dezimalstellen",
        suggestion_template="Reduziere Dezimalstellen auf 0-1 fuer bessere Lesbarkeit",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="CO-T-04.6",
        category="CONDENSE",
        name="Zahlen ohne Rundung",
        description="Sehr genaue Zahlen erfordern Rundung auf angemessene Praezision",
        check_type="metadata",
        severity="info",
        violation_hint="Zahlen haben viele signifikante Stellen ohne Rundung",
        suggestion_template="Runde Zahlen auf angemessene Praezision fuer bessere Lesbarkeit",
        applies_to=['xlsx', 'pptx'],
    ),
    IBCSRule(
        id="CO-T-04.7",
        category="CONDENSE",
        name="Zahlen als Text formatiert",
        description="Zahlenwerte in Textzellen koennen nicht sortiert/berechnet werden",
        check_type="metadata",
        severity="error",
        violation_hint="Zahlenwerte sind als Text formatiert, nicht als Zahl",
        suggestion_template="Konvertiere Text-Zahlen in echte numerische Zellformate",
        applies_to=['xlsx'],
    ),
]

# ---------------------------------------------------------------------------
# CH-CHECK table rules
# ---------------------------------------------------------------------------
CH_TABLE_RULES: List[IBCSRule] = [
    # CH-T-01: Math correctness
    IBCSRule(
        id="CH-T-01.1",
        category="CHECK",
        name="Summenzeile rechnerisch falsch",
        description="Summenzeilen muessen die Summe der Detailzeilen ergeben",
        check_type="metadata",
        severity="error",
        violation_hint="Summenzeile ergibt nicht die Summe der Unterpositionen",
        suggestion_template="Korrigiere Summenformel in der Summenzeile",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="CH-T-01.2",
        category="CHECK",
        name="Abweichung nicht als AC minus Plan berechnet",
        description="Abweichung muss exakt als AC-PL berechnet sein",
        check_type="metadata",
        severity="error",
        violation_hint="Abweichungswert stimmt nicht mit AC minus PL ueberein",
        suggestion_template="Korrigiere Formel: Abweichung = AC - PL",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="CH-T-01.3",
        category="CHECK",
        name="Formel-Fehler in Zelle",
        description="Zellen mit Formel-Fehlern (REF, DIV0 etc.) muessen behoben werden",
        check_type="metadata",
        severity="error",
        violation_hint="Zelle zeigt Formel-Fehler wie REF! oder DIV/0!",
        suggestion_template="Behebe Formel-Fehler in den betroffenen Zellen",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="CH-T-01.4",
        category="CHECK",
        name="Inkonsistente Summenformeln",
        description="Summenformeln in gleichen Positionen sollen konsistent sein",
        check_type="metadata",
        severity="error",
        violation_hint="Summenformeln referenzieren unterschiedliche Zellbereiche",
        suggestion_template="Vereinheitliche Summenformeln fuer gleiche Positionen",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="CH-T-01.5",
        category="CHECK",
        name="Harte Zahlen statt Formeln",
        description="Hartcodierte Zahlen statt Formeln machen Fehler schwer erkennbar",
        check_type="metadata",
        severity="warning",
        violation_hint="Summenzeile enthaelt harte Zahlen statt Summenformeln",
        suggestion_template="Ersetze hartcodierte Summen durch Summenformeln",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="CH-T-01.6",
        category="CHECK",
        name="Abweichungsprozent rechnerisch falsch",
        description="Relative Abweichung muss als absolute Abweichung geteilt durch Basis berechnet werden",
        check_type="metadata",
        severity="error",
        violation_hint="Abweichungsprozent stimmt nicht mit abs. Abweichung / Basis ueberein",
        suggestion_template="Korrigiere Formel: % = DeltaAC-PL / PL",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="CH-T-01.7",
        category="CHECK",
        name="Formel-Fehler REF oder DIV0",
        description="Zellen mit REF! oder DIV/0! Fehlern muessen korrigiert werden",
        check_type="metadata",
        severity="error",
        violation_hint="Formel-Fehler gefunden: REF!, DIV/0!, NAME! oder WERT!",
        suggestion_template="Behebe alle Formel-Fehler in der Tabelle",
        applies_to=['xlsx'],
    ),
    # CH-T-02: Scale consistency
    IBCSRule(
        id="CH-T-02.1",
        category="CHECK",
        name="Inkonsistente Skalierung in Dokument",
        description="Gleiche Groessen muessen in allen Tabellen gleich skaliert sein",
        check_type="metadata",
        severity="error",
        violation_hint="Umsatz in einer Tabelle in T€, in anderer in Mio.€",
        suggestion_template="Vereinheitliche Skalierung fuer gleiche Groessen im gesamten Dokument",
        applies_to=['xlsx', 'pptx'],
    ),
    IBCSRule(
        id="CH-T-02.2",
        category="CHECK",
        name="Skalierung nicht im Header angegeben",
        description="Skalierungsfaktor muss im Spaltenkopf oder Titel erkennbar sein",
        check_type="metadata",
        severity="error",
        violation_hint="Kein Hinweis auf Skalierung (T€, Mio.€) im Spaltenkopf",
        suggestion_template="Ergaenze Skalierungseinheit explizit im Spaltenkopf",
        applies_to=['xlsx', 'pptx'],
    ),
    IBCSRule(
        id="CH-T-02.3",
        category="CHECK",
        name="Werte zu gross fuer angegebene Einheit",
        description="Wertgroessenordnung passt nicht zur angegebenen Einheit",
        check_type="metadata",
        severity="warning",
        violation_hint="Zahlenwerte erscheinen zu gross oder zu klein fuer die angegebene Einheit",
        suggestion_template="Pruefe ob Einheit und Werte konsistent sind",
        applies_to=['xlsx', 'pptx'],
    ),
    IBCSRule(
        id="CH-T-02.4",
        category="CHECK",
        name="Skalierungswechsel ohne Kennzeichnung",
        description="Skalierung darf sich nicht unangekuendigt aendern",
        check_type="metadata",
        severity="error",
        violation_hint="Skalierung wechselt im Dokument ohne explizite Kennzeichnung",
        suggestion_template="Kennzeichne Skalierungswechsel explizit im Header",
        applies_to=['xlsx', 'pptx'],
    ),
    # CH-T-03: Completeness
    IBCSRule(
        id="CH-T-03.1",
        category="CHECK",
        name="Leere Zellen in Wertspalten",
        description="Leere Zellen in Wertspalten muessen erklaert werden",
        check_type="metadata",
        severity="warning",
        violation_hint="Wertspalte enthaelt leere Zellen ohne erkennbaren Grund",
        suggestion_template="Fuege Wert, NA oder Gedankenstrich in leere Wertzellen ein",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="CH-T-03.2",
        category="CHECK",
        name="Nicht alle Szenarien vorhanden",
        description="Wenn AC vorhanden soll auch PY und PL vorhanden sein",
        check_type="metadata",
        severity="warning",
        violation_hint="AC-Spalte vorhanden aber PY oder PL fehlen",
        suggestion_template="Ergaenze fehlende Szenario-Spalten oder erklaere Abwesenheit",
        applies_to=['xlsx', 'pptx'],
    ),
    IBCSRule(
        id="CH-T-03.3",
        category="CHECK",
        name="Fehlende Periode in Zeitreihe",
        description="Alle erwarteten Zeitperioden muessen vorhanden sein",
        check_type="metadata",
        severity="warning",
        violation_hint="Zeitreihe hat Luecken bei erwarteten Perioden",
        suggestion_template="Ergaenze fehlende Zeitperioden oder kennzeichne Luecken explizit",
        applies_to=['xlsx', 'pptx'],
    ),
    IBCSRule(
        id="CH-T-03.4",
        category="CHECK",
        name="Inkomplette Hierarchie",
        description="Summenzeile ohne alle zugehoerigen Detailzeilen ist inkomplett",
        check_type="metadata",
        severity="error",
        violation_hint="Summenzeile hat weniger Detailzeilen als erwartet",
        suggestion_template="Ergaenze fehlende Detailzeilen oder entferne die Summenzeile",
        applies_to=['xlsx', 'pptx'],
    ),
    # CH-T-04: Period consistency
    IBCSRule(
        id="CH-T-04.1",
        category="CHECK",
        name="PY entspricht nicht Vorjahres-AC",
        description="PY-Werte muessen mit den AC-Werten des Vorjahres uebereinstimmen",
        check_type="metadata",
        severity="error",
        violation_hint="PY-Werte weichen von Vorjahres-AC-Werten ab",
        suggestion_template="Stelle sicher dass PY-Werte dem AC des Vorjahres entsprechen",
        applies_to=['xlsx', 'pptx'],
    ),
    IBCSRule(
        id="CH-T-04.2",
        category="CHECK",
        name="Restated-Werte nicht gekennzeichnet",
        description="Angepasste Vorjahreswerte muessen als restated markiert sein",
        check_type="metadata",
        severity="warning",
        violation_hint="Vorjahreswerte wurden angepasst aber nicht als restated markiert",
        suggestion_template="Kennzeichne angepasste Vorjahreswerte mit Fussnote (restated)",
        applies_to=['xlsx', 'pptx'],
    ),
    IBCSRule(
        id="CH-T-04.3",
        category="CHECK",
        name="Inkonsistente Periodenabgrenzung",
        description="Gleiche Perioden muessen in allen Tabellen gleich abgegrenzt sein",
        check_type="metadata",
        severity="error",
        violation_hint="Periodenabgrenzung fuer gleiche Zeitraeume ist inkonsistent",
        suggestion_template="Vereinheitliche Periodenabgrenzung fuer gleiche Zeitraeume",
        applies_to=['xlsx', 'pptx'],
    ),
]

# ---------------------------------------------------------------------------
# SI-SIMPLIFY table rules
# ---------------------------------------------------------------------------
SI_TABLE_RULES: List[IBCSRule] = [
    # SI-T-01: No unit repetition
    IBCSRule(
        id="SI-T-01.1",
        category="SIMPLIFY",
        name="Einheiten-Wiederholung in Zellen",
        description="Einheiten gehoeren in den Header, nicht in jede Datenzelle",
        check_type="metadata",
        severity="error",
        violation_hint="Einheitensymbol wird in jeder Datenzelle wiederholt",
        suggestion_template="Platziere Einheit einmalig im Spaltenkopf",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="SI-T-01.2",
        category="SIMPLIFY",
        name="Duplizierte Spalten",
        description="Identische Inhalte in mehreren Spalten sind redundant",
        check_type="metadata",
        severity="error",
        violation_hint="Tabelle enthaelt zwei oder mehr identische Spalten",
        suggestion_template="Entferne duplizierte Spalten aus der Tabelle",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="SI-T-01.3",
        category="SIMPLIFY",
        name="Redundante Prozentwerte",
        description="Prozentwerte die aus absoluten Werten berechenbar sind sind redundant",
        check_type="metadata",
        severity="info",
        violation_hint="Tabelle hat sowohl Absolutwerte als auch berechenbare Prozentwerte",
        suggestion_template="Erwaege ob Prozentwerte wirklich zusaetzlichen Informationswert haben",
        applies_to=['xlsx', 'pptx'],
    ),
    IBCSRule(
        id="SI-T-01.4",
        category="SIMPLIFY",
        name="Datum-Wiederholung in Zeilen",
        description="Datum oder Periode wird in jeder Zeile wiederholt statt im Header",
        check_type="metadata",
        severity="warning",
        violation_hint="Datums- oder Periodenangabe in jeder Datenzeile wiederholt",
        suggestion_template="Platziere Periodenangabe im Spaltenkopf statt in Datenzellen",
        applies_to=['xlsx', 'pptx'],
    ),
    IBCSRule(
        id="SI-T-01.5",
        category="SIMPLIFY",
        name="Redundante Summenspalte",
        description="Gesamtsumme-Spalte wenn nur eine Szenario-Spalte vorhanden",
        check_type="metadata",
        severity="info",
        violation_hint="Totalspalte dupliziert die einzige Wertspalte",
        suggestion_template="Pruefe ob Totalspalte bei nur einem Szenario wirklich benoetigt wird",
        applies_to=['xlsx', 'pptx'],
    ),
    IBCSRule(
        id="SI-T-01.6",
        category="SIMPLIFY",
        name="Szenario-Label in Datenzellen",
        description="Szenario-Bezeichnung in jeder Datenzelle ist redundant",
        check_type="metadata",
        severity="warning",
        violation_hint="Szenario-Bezeichnung (z.B. Ist) wird in Datenzellen wiederholt",
        suggestion_template="Platziere Szenario-Bezeichnung nur im Spaltenkopf",
        applies_to=['xlsx', 'pptx'],
    ),
    # SI-T-02: No decoration
    IBCSRule(
        id="SI-T-02.1",
        category="SIMPLIFY",
        name="Farbverlauf-Fuellung",
        description="Farbverlaeufe in Tabellenzellen sind nach IBCS nicht erlaubt",
        check_type="metadata",
        severity="error",
        violation_hint="Zellen oder Kopfzeilen haben Farbverlauf-Fuellung",
        suggestion_template="Ersetze Farbverlaeufe durch einfarbige Fuellung",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="SI-T-02.2",
        category="SIMPLIFY",
        name="3D-Effekte in Tabelle",
        description="3D-Effekte an Tabellen-Elementen sind nicht erlaubt",
        check_type="metadata",
        severity="error",
        violation_hint="Tabelle oder Zellen haben 3D-Effekte oder Schatten",
        suggestion_template="Entferne alle 3D-Effekte und Schatten aus der Tabelle",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="SI-T-02.3",
        category="SIMPLIFY",
        name="Unnoetige Gitterlinien",
        description="Uebertrieben viele Gitterlinien erhoehen visuelle Komplexitaet",
        check_type="metadata",
        severity="warning",
        violation_hint="Tabelle hat horizontale und vertikale Gitterlinien fuer alle Zellen",
        suggestion_template="Reduziere Gitterlinien auf notwendiges Minimum",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="SI-T-02.4",
        category="SIMPLIFY",
        name="Dekorative Rahmen ohne Funktion",
        description="Rahmen um Tabellen-Elemente ohne strukturellen Zweck",
        check_type="metadata",
        severity="info",
        violation_hint="Tabelle hat dekorative Rahmen ohne strukturelle Funktion",
        suggestion_template="Entferne dekorative Rahmen aus der Tabelle",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="SI-T-02.5",
        category="SIMPLIFY",
        name="Dekoratives Logo in Tabelle",
        description="Logos oder Bilder in Tabellen ohne Informationswert",
        check_type="metadata",
        severity="info",
        violation_hint="Tabelle enthaelt dekoratives Logo oder Bild",
        suggestion_template="Entferne Dekorationselemente aus der Tabelle",
        applies_to=['xlsx', 'pptx'],
    ),
    IBCSRule(
        id="SI-T-02.6",
        category="SIMPLIFY",
        name="Alternating Row Colors dekorativ",
        description="Zeilenfarben zur Dekoration ohne semantischen Zweck",
        check_type="metadata",
        severity="info",
        violation_hint="Tabelle hat abwechselnde Zeilenfarben ohne IBCS-Semantik",
        suggestion_template="Verwende Zeilenfarben nur fuer semantische Unterscheidung",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="SI-T-02.7",
        category="SIMPLIFY",
        name="Uebermaessig fette Rahmenlinien",
        description="Sehr dicke Rahmenlinien lenken vom Inhalt ab",
        check_type="metadata",
        severity="info",
        violation_hint="Tabelle hat sehr dicke Rahmenlinien",
        suggestion_template="Reduziere Rahmenliniendice auf maximal 0.5pt fuer Datenzellen",
        applies_to=['xlsx'],
    ),
    # SI-T-03: Font reduction
    IBCSRule(
        id="SI-T-03.1",
        category="SIMPLIFY",
        name="Mehr als 2 Schriftstaerken",
        description="IBCS empfiehlt maximal 2 Schriftstaerken in Tabellen",
        check_type="metadata",
        severity="warning",
        violation_hint="Tabelle verwendet mehr als 2 Schriftstaerken (z.B. normal, halbfett, fett)",
        suggestion_template="Reduziere auf maximal 2 Schriftstaerken: normal und fett",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="SI-T-03.2",
        category="SIMPLIFY",
        name="Mehrere Schriftfamilien",
        description="In einer Tabelle soll nur eine Schriftfamilie verwendet werden",
        check_type="metadata",
        severity="warning",
        violation_hint="Tabelle verwendet mehrere Schriftfamilien",
        suggestion_template="Vereinheitliche auf eine Schriftfamilie fuer die gesamte Tabelle",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="SI-T-03.3",
        category="SIMPLIFY",
        name="Serifen-Schrift in Tabelle",
        description="IBCS empfiehlt serifenlose Schriften fuer Tabellen",
        check_type="metadata",
        severity="info",
        violation_hint="Tabelle verwendet eine Serifen-Schrift",
        suggestion_template="Ersetze Serifen-Schrift durch serifenlose Schrift wie Arial oder Calibri",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="SI-T-03.4",
        category="SIMPLIFY",
        name="Mehr als 4 Schriftgroessen",
        description="Zu viele Schriftgroessen erhoehen visuelle Komplexitaet",
        check_type="metadata",
        severity="warning",
        violation_hint="Tabelle verwendet mehr als 4 verschiedene Schriftgroessen",
        suggestion_template="Reduziere auf maximal 3 Schriftgroessen: Header, Daten, Fussnoten",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="SI-T-03.5",
        category="SIMPLIFY",
        name="Textformatierung als Daten-Kodierung",
        description="Kursiv oder fett als einziges Unterscheidungsmerkmal ist unsicher",
        check_type="metadata",
        severity="info",
        violation_hint="Schriftformatierung allein unterscheidet Datentypen ohne Farbunterstuetzung",
        suggestion_template="Kombiniere Schriftformatierung mit Farbe fuer Szenario-Unterscheidung",
        applies_to=['xlsx'],
    ),
    # SI-T-04: Row label brevity
    IBCSRule(
        id="SI-T-04.1",
        category="SIMPLIFY",
        name="Zu lange Zeilenbeschriftungen",
        description="Zeilenbeschriftungen sollen praezise und kurz sein",
        check_type="metadata",
        severity="info",
        violation_hint="Zeilenbeschriftungen sind laenger als 40 Zeichen",
        suggestion_template="Kuerze Zeilenbeschriftungen auf wesentliche Kernaussage",
        applies_to=['xlsx', 'pptx'],
    ),
    IBCSRule(
        id="SI-T-04.2",
        category="SIMPLIFY",
        name="Abkuerzungen in Zeilenbeschriftungen",
        description="Verwendete Abkuerzungen muessen erklaert werden",
        check_type="metadata",
        severity="info",
        violation_hint="Zeilenbeschriftungen enthalten unerklichte Abkuerzungen",
        suggestion_template="Erklaere Abkuerzungen in Fussnoten oder verwende Vollbezeichnungen",
        applies_to=['xlsx', 'pptx'],
    ),
    IBCSRule(
        id="SI-T-04.3",
        category="SIMPLIFY",
        name="Wiederholende Worte in Zeilenlabels",
        description="Gemeinsame Bestandteile sollen in Gruppenheader verschoben werden",
        check_type="metadata",
        severity="info",
        violation_hint="Viele Zeilenlabels wiederholen dasselbe Wort (z.B. Kosten Vertrieb, Kosten Marketing)",
        suggestion_template="Verschiebe gemeinsame Bestandteile in Gruppenheader",
        applies_to=['xlsx', 'pptx'],
    ),
]

# ---------------------------------------------------------------------------
# ST-STRUCTURE table rules
# ---------------------------------------------------------------------------
ST_TABLE_RULES: List[IBCSRule] = [
    # ST-T-01: Row hierarchy
    IBCSRule(
        id="ST-T-01.1",
        category="STRUCTURE",
        name="Fehlende Einrueckung bei Hierarchie",
        description="Untergeordnete Zeilen muessen eingerueckt werden",
        check_type="metadata",
        severity="error",
        violation_hint="Hierarchie-Stufen ohne Einrueckung in Zeilenbeschriftungen",
        suggestion_template="Fuege Einrueckung fuer Unterpositionen hinzu",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="ST-T-01.2",
        category="STRUCTURE",
        name="Inkonsistente Einrueckungstiefe",
        description="Gleiche Hierarchiestufen muessen gleich tief eingerueckt sein",
        check_type="metadata",
        severity="warning",
        violation_hint="Gleichrangige Positionen haben unterschiedliche Einrueckungstiefe",
        suggestion_template="Vereinheitliche Einrueckungstiefe pro Hierarchiestufe",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="ST-T-01.3",
        category="STRUCTURE",
        name="Summenzeile unten statt oben",
        description="IBCS platziert Summenzeilen ueber den Detailzeilen",
        check_type="metadata",
        severity="warning",
        violation_hint="Summenzeile steht unterhalb der Detailzeilen",
        suggestion_template="Platziere Summenzeile oberhalb der zugehoerigen Detailzeilen",
        applies_to=['xlsx', 'pptx'],
    ),
    IBCSRule(
        id="ST-T-01.4",
        category="STRUCTURE",
        name="Fehlende Summenzeilen",
        description="Jede Hierarchieebene benoetigt eine Summenzeile",
        check_type="metadata",
        severity="warning",
        violation_hint="Detailzeilen ohne zugehoerige Summenzeile vorhanden",
        suggestion_template="Ergaenze Summenzeile fuer jede Hierarchiegruppe",
        applies_to=['xlsx', 'pptx'],
    ),
    IBCSRule(
        id="ST-T-01.5",
        category="STRUCTURE",
        name="Summenzeile nicht visuell hervorgehoben",
        description="Summenzeilen muessen visuell klar erkennbar sein",
        check_type="metadata",
        severity="warning",
        violation_hint="Summenzeile ist nicht durch Fettschrift oder Rahmen hervorgehoben",
        suggestion_template="Hebe Summenzeilen durch Fettschrift oder Trennlinie hervor",
        applies_to=['xlsx', 'pptx'],
    ),
    IBCSRule(
        id="ST-T-01.6",
        category="STRUCTURE",
        name="Zu viele Hierarchieebenen",
        description="Mehr als 3 Hierarchieebenen machen Tabellen unuebersichtlich",
        check_type="metadata",
        severity="info",
        violation_hint="Tabelle hat mehr als 3 Hierarchieebenen in Zeilen",
        suggestion_template="Reduziere Hierarchietiefe auf maximal 3 Ebenen",
        applies_to=['xlsx', 'pptx'],
    ),
    IBCSRule(
        id="ST-T-01.7",
        category="STRUCTURE",
        name="Fehlende Trennlinie nach Hierarchiegruppe",
        description="Trennlinien zwischen Gruppen verbessern Lesbarkeit",
        check_type="metadata",
        severity="info",
        violation_hint="Keine Trennlinien zwischen Hierarchiegruppen",
        suggestion_template="Ergaenze subtile Trennlinien zwischen Hauptgruppen",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="ST-T-01.8",
        category="STRUCTURE",
        name="Inkonsistente Hierarchie-Farben",
        description="Hierarchiestufen muessen konsistent farblich unterschieden sein",
        check_type="metadata",
        severity="warning",
        violation_hint="Gleiche Hierarchiestufen haben unterschiedliche Hintergrundfarben",
        suggestion_template="Vereinheitliche Farbkodierung pro Hierarchiestufe",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="ST-T-01.9",
        category="STRUCTURE",
        name="Detailzeilen ohne Summenzeile",
        description="Jede Gruppe von Detailzeilen braucht eine Summenzeile",
        check_type="metadata",
        severity="warning",
        violation_hint="Mehrere Detailzeilen ohne uebergeordnete Summenzeile",
        suggestion_template="Ergaenze Summenzeile fuer jede Detailzeilen-Gruppe",
        applies_to=['xlsx', 'pptx'],
    ),
    IBCSRule(
        id="ST-T-01.10",
        category="STRUCTURE",
        name="Zeilen-Sortierung nicht logisch",
        description="Zeilen sollen logisch oder nach Groesse sortiert sein",
        check_type="metadata",
        severity="info",
        violation_hint="Zeilensortierung erscheint willkuerlich oder zufaellig",
        suggestion_template="Sortiere Zeilen logisch: Wichtigstes oben oder nach Wertgroesse",
        applies_to=['xlsx', 'pptx'],
    ),
    # ST-T-02: Column hierarchy
    IBCSRule(
        id="ST-T-02.1",
        category="STRUCTURE",
        name="Fehlende Szenario-Spaltengruppen",
        description="Zusammengehoerige Szenario-Spalten sollen gruppiert sein",
        check_type="metadata",
        severity="warning",
        violation_hint="AC-Spalten und PL-Spalten sind nicht als Gruppen erkennbar",
        suggestion_template="Gruppiere zusammengehoerige Szenario-Spalten mit Gruppenheader",
        applies_to=['xlsx', 'pptx'],
    ),
    IBCSRule(
        id="ST-T-02.2",
        category="STRUCTURE",
        name="Fehlende verbundene Headerzeile",
        description="Spaltengruppen-Header muessen verbundene Zellen verwenden",
        check_type="metadata",
        severity="warning",
        violation_hint="Spaltengruppen ohne verbundene Kopfzeile",
        suggestion_template="Verbinde Zellen fuer Spaltengruppen-Header",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="ST-T-02.3",
        category="STRUCTURE",
        name="Fehlende Abstandsspalten zwischen Szenarien",
        description="Abstandsspalten zwischen Szenario-Gruppen verbessern Lesbarkeit",
        check_type="metadata",
        severity="info",
        violation_hint="Keine Abstandsspalten zwischen AC- und PL-Spaltengruppe",
        suggestion_template="Ergaenze schmale Abstandsspalten zwischen Szenario-Gruppen",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="ST-T-02.4",
        category="STRUCTURE",
        name="Falsche Spaltenreihenfolge",
        description="IBCS-Spaltenreihenfolge: Label, dann AC, dann PY, dann PL, dann Delta",
        check_type="metadata",
        severity="warning",
        violation_hint="Spalten sind nicht in IBCS-konformer Reihenfolge angeordnet",
        suggestion_template="Sortiere Spalten gemaess IBCS: AC, PY, PL, FC, dann Abweichungen",
        applies_to=['xlsx', 'pptx'],
    ),
    IBCSRule(
        id="ST-T-02.5",
        category="STRUCTURE",
        name="Label-Spalte nicht an erster Stelle",
        description="Zeilenbeschriftungen muessen in der ersten Spalte stehen",
        check_type="metadata",
        severity="error",
        violation_hint="Zeilenbeschriftungen sind nicht in der ersten Spalte",
        suggestion_template="Platziere Zeilenbeschriftungen immer in der ersten Spalte",
        applies_to=['xlsx', 'pptx'],
    ),
    IBCSRule(
        id="ST-T-02.6",
        category="STRUCTURE",
        name="Zu viele Spalten fuer eine Seite",
        description="Zu viele Spalten machen Tabellen unuebersichtlich",
        check_type="metadata",
        severity="warning",
        violation_hint="Tabelle hat mehr Spalten als auf einer Seite gut lesbar",
        suggestion_template="Reduziere Spaltenanzahl oder teile Tabelle auf mehrere Seiten",
        applies_to=['xlsx', 'pptx'],
    ),
    IBCSRule(
        id="ST-T-02.7",
        category="STRUCTURE",
        name="Inkonsistente Spaltenreihenfolge",
        description="Spaltenreihenfolge muss in allen Tabellen des Dokuments gleich sein",
        check_type="metadata",
        severity="warning",
        violation_hint="Spalten sind in verschiedenen Tabellen unterschiedlich angeordnet",
        suggestion_template="Vereinheitliche Spaltenreihenfolge im gesamten Dokument",
        applies_to=['xlsx', 'pptx'],
    ),
    # ST-T-03: Header rows
    IBCSRule(
        id="ST-T-03.1",
        category="STRUCTURE",
        name="Fehlende Kopfzeile",
        description="Tabellen brauchen mindestens eine Kopfzeile",
        check_type="metadata",
        severity="error",
        violation_hint="Tabelle hat keine erkennbare Kopfzeile",
        suggestion_template="Ergaenze mindestens eine Kopfzeile mit Spaltenbezeichnungen",
        applies_to=['xlsx', 'pptx'],
    ),
    IBCSRule(
        id="ST-T-03.2",
        category="STRUCTURE",
        name="Nur eine Kopfzeile",
        description="IBCS empfiehlt mindestens zwei Kopfzeilen (Gruppe und Detail)",
        check_type="metadata",
        severity="warning",
        violation_hint="Tabelle hat nur eine Kopfzeile statt mindestens zwei",
        suggestion_template="Ergaenze zweite Kopfzeile fuer Szenario-Gruppen und Details",
        applies_to=['xlsx', 'pptx'],
    ),
    IBCSRule(
        id="ST-T-03.3",
        category="STRUCTURE",
        name="Kopfzeile nicht optisch abgegrenzt",
        description="Kopfzeile muss visuell klar vom Datenbereich abgegrenzt sein",
        check_type="metadata",
        severity="warning",
        violation_hint="Kopfzeile ist optisch nicht klar vom Datenbereich getrennt",
        suggestion_template="Hebe Kopfzeile durch Hintergrundfarbe oder Trennlinie hervor",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="ST-T-03.4",
        category="STRUCTURE",
        name="Kopfzeile enthaelt Datenwerte",
        description="Kopfzeilen sollen nur Bezeichnungen enthalten keine Datenwerte",
        check_type="metadata",
        severity="error",
        violation_hint="Kopfzeile enthaelt Datenwerte statt nur Bezeichnungen",
        suggestion_template="Trenne Kopfzeilen (Bezeichnungen) von Datenzeilen (Werte)",
        applies_to=['xlsx', 'pptx'],
    ),
    IBCSRule(
        id="ST-T-03.5",
        category="STRUCTURE",
        name="Szenario-Kuerzel nicht in Kopfzeile",
        description="AC/PY/PL/FC-Kuerzel gehoeren in die Kopfzeile",
        check_type="metadata",
        severity="error",
        violation_hint="Szenario-Kuerzel erscheinen nicht in der Kopfzeile",
        suggestion_template="Platziere Szenario-Kuerzel AC/PY/PL/FC in der Kopfzeile",
        applies_to=['xlsx', 'pptx'],
    ),
    IBCSRule(
        id="ST-T-03.6",
        category="STRUCTURE",
        name="Kopfzeile ohne Zeitperioden-Angabe",
        description="Zeitperioden-Spalten muessen Periode in Kopfzeile haben",
        check_type="metadata",
        severity="warning",
        violation_hint="Zeitperioden-Spalten haben keine Periodenangabe in der Kopfzeile",
        suggestion_template="Ergaenze Zeitperiode in der Kopfzeile z.B. Jan 2024",
        applies_to=['xlsx', 'pptx'],
    ),
    IBCSRule(
        id="ST-T-03.7",
        category="STRUCTURE",
        name="Mehrdeutige Spaltenbezeichnung",
        description="Spaltenbezeichnungen muessen eindeutig und unmissverstaendlich sein",
        check_type="metadata",
        severity="warning",
        violation_hint="Spaltenbezeichnung ist mehrdeutig oder unklar",
        suggestion_template="Verwende eindeutige, unmissverstaendliche Spaltenbezeichnungen",
        applies_to=['xlsx', 'pptx'],
    ),
    # ST-T-04: Title and labeling
    IBCSRule(
        id="ST-T-04.1",
        category="STRUCTURE",
        name="Fehlender Tabellentitel",
        description="Jede Tabelle braucht einen Titel mit Thema und Zeitraum",
        check_type="metadata",
        severity="error",
        violation_hint="Tabelle hat keinen erkennbaren Titel",
        suggestion_template="Ergaenze Tabellentitel mit Thema, Zeitraum und Org-Einheit",
        applies_to=['xlsx', 'pptx'],
    ),
    IBCSRule(
        id="ST-T-04.2",
        category="STRUCTURE",
        name="Titel ohne Themen-Angabe",
        description="Tabellentitel muss das Thema der Tabelle nennen",
        check_type="metadata",
        severity="error",
        violation_hint="Tabellentitel enthaelt keine Themen-Angabe",
        suggestion_template="Ergaenze Thema im Tabellentitel z.B. Umsatz nach Region",
        applies_to=['xlsx', 'pptx'],
    ),
    IBCSRule(
        id="ST-T-04.3",
        category="STRUCTURE",
        name="Titel ohne Zeitraum",
        description="Tabellentitel muss den dargestellten Zeitraum enthalten",
        check_type="metadata",
        severity="warning",
        violation_hint="Tabellentitel enthaelt keine Zeitraums-Angabe",
        suggestion_template="Ergaenze Zeitraum im Tabellentitel z.B. Jan-Dez 2024",
        applies_to=['xlsx', 'pptx'],
    ),
    IBCSRule(
        id="ST-T-04.4",
        category="STRUCTURE",
        name="Titel ohne Organisations-Einheit",
        description="Tabellentitel soll die betroffene Org-Einheit enthalten",
        check_type="metadata",
        severity="info",
        violation_hint="Tabellentitel enthaelt keine Angabe zur Organisations-Einheit",
        suggestion_template="Ergaenze Org-Einheit im Tabellentitel wenn relevant",
        applies_to=['xlsx', 'pptx'],
    ),
    IBCSRule(
        id="ST-T-04.5",
        category="STRUCTURE",
        name="Titel ohne Einheit",
        description="Tabellentitel soll die verwendete Einheit enthalten",
        check_type="metadata",
        severity="warning",
        violation_hint="Tabellentitel enthaelt keine Einheitsangabe",
        suggestion_template="Ergaenze Einheit im Tabellentitel z.B. in T€",
        applies_to=['xlsx', 'pptx'],
    ),
    IBCSRule(
        id="ST-T-04.6",
        category="STRUCTURE",
        name="Fehlende Org-Einheit-Angabe",
        description="Organisationseinheit-Bezug der Tabelle muss erkennbar sein",
        check_type="metadata",
        severity="info",
        violation_hint="Tabelle hat keinen Hinweis auf die dargestellte Organisationseinheit",
        suggestion_template="Ergaenze Hinweis auf Organisationseinheit in Titel oder Header",
        applies_to=['xlsx', 'pptx'],
    ),
    # ST-T-05: Footnotes
    IBCSRule(
        id="ST-T-05.1",
        category="STRUCTURE",
        name="Fussnoten nicht nummeriert",
        description="Fussnoten muessen durchnummeriert und der Bezugszelle zugeordnet sein",
        check_type="metadata",
        severity="warning",
        violation_hint="Fussnoten ohne Nummerierung oder Bezug zur Datenzelle",
        suggestion_template="Nummeriere Fussnoten und kennzeichne Bezugszellen entsprechend",
        applies_to=['xlsx', 'pptx'],
    ),
    IBCSRule(
        id="ST-T-05.2",
        category="STRUCTURE",
        name="Restated-Werte ohne Fussnote",
        description="Angepasste Vorjahreswerte brauchen eine erklaerende Fussnote",
        check_type="metadata",
        severity="warning",
        violation_hint="Restated-Werte ohne erklaerenende Fussnote vorhanden",
        suggestion_template="Ergaenze Fussnote mit Erklaerung fuer restated-Werte",
        applies_to=['xlsx', 'pptx'],
    ),
    IBCSRule(
        id="ST-T-05.3",
        category="STRUCTURE",
        name="Fehlende Datenstand-Angabe",
        description="Datenstand oder Abrufdatum der Daten soll angegeben sein",
        check_type="metadata",
        severity="info",
        violation_hint="Kein Hinweis auf Datenstand oder Abrufdatum",
        suggestion_template="Ergaenze Datenstand-Angabe als Fussnote z.B. Stand 31.03.2024",
        applies_to=['xlsx', 'pptx'],
    ),
    IBCSRule(
        id="ST-T-05.4",
        category="STRUCTURE",
        name="Fussnoten-Text unleserlich",
        description="Fussnoten-Text muss mindestens 7pt gross sein",
        check_type="metadata",
        severity="warning",
        violation_hint="Fussnoten sind kleiner als 7pt und schwer lesbar",
        suggestion_template="Ergroessere Fussnoten-Text auf mindestens 7pt",
        applies_to=['xlsx', 'pptx'],
    ),
]

# ---------------------------------------------------------------------------
# SA-SAY table rules
# ---------------------------------------------------------------------------
SA_TABLE_RULES: List[IBCSRule] = [
    # SA-T-01: Core message
    IBCSRule(
        id="SA-T-01.1",
        category="SAY",
        name="Kein Aussage-Titel in Tabelle",
        description="Tabellentitel soll eine Kernaussage formulieren nicht nur ein Thema",
        check_type="metadata",
        severity="error",
        violation_hint="Tabellentitel ist nur ein Substantiv ohne Aussage",
        suggestion_template="Formuliere Tabellentitel als Aussage z.B. Umsatz steigt um 12%",
        applies_to=['xlsx', 'pptx'],
    ),
    IBCSRule(
        id="SA-T-01.2",
        category="SAY",
        name="Fehlender Kommentar zur Kernaussage",
        description="Bedeutsame Abweichungen oder Trends brauchen Kommentar",
        check_type="metadata",
        severity="info",
        violation_hint="Tabelle zeigt bedeutsame Abweichungen ohne erlaeuternden Kommentar",
        suggestion_template="Ergaenze Kommentar der auf die wesentliche Aussage hinweist",
        applies_to=['xlsx', 'pptx'],
    ),
    IBCSRule(
        id="SA-T-01.3",
        category="SAY",
        name="Hervorhebung stimmt nicht mit Titel-Aussage ueberein",
        description="Hervorgehobene Zellen muessen der Titel-Aussage entsprechen",
        check_type="metadata",
        severity="warning",
        violation_hint="Hervorgehobene Bereiche passen nicht zur Aussage im Titel",
        suggestion_template="Stelle sicher dass Hervorhebungen die Titel-Aussage unterstuetzen",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="SA-T-01.4",
        category="SAY",
        name="Keine Hervorhebung wichtiger Werte",
        description="Schluessel-Datenpunkte sollen visuell hervorgehoben sein",
        check_type="metadata",
        severity="info",
        violation_hint="Tabelle hat keine Hervorhebung wichtiger oder auffaelliger Werte",
        suggestion_template="Hebe die wichtigsten Datenpunkte visuell hervor",
        applies_to=['xlsx', 'pptx'],
    ),
    # SA-T-02: Highlighting
    IBCSRule(
        id="SA-T-02.1",
        category="SAY",
        name="Zu viele hervorgehobene Bereiche",
        description="Maximal 1-3 Bereiche sollen hervorgehoben sein",
        check_type="metadata",
        severity="warning",
        violation_hint="Mehr als 3 verschiedene Bereiche sind hervorgehoben",
        suggestion_template="Reduziere Hervorhebungen auf die 1-3 wichtigsten Bereiche",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="SA-T-02.2",
        category="SAY",
        name="Hervorhebungsfarbe nicht markant genug",
        description="Hervorhebungsfarbe muss sich klar von anderen Farben unterscheiden",
        check_type="metadata",
        severity="warning",
        violation_hint="Hervorhebungsfarbe ist zu aehnlich wie andere Tabellenfarben",
        suggestion_template="Verwende eine klar unterscheidbare Farbe fuer Hervorhebungen",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="SA-T-02.3",
        category="SAY",
        name="Inkonsistente Hervorhebungsmethode",
        description="Hervorhebungen sollen im Dokument konsistent verwendet werden",
        check_type="metadata",
        severity="warning",
        violation_hint="Verschiedene Hervorhebungsmethoden (Farbe, Rahmen, Schrift) gemischt",
        suggestion_template="Vereinheitliche Hervorhebungsmethode im gesamten Dokument",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="SA-T-02.4",
        category="SAY",
        name="Hervorhebung ohne erkennbaren Grund",
        description="Jede Hervorhebung soll einen erkennbaren inhaltlichen Grund haben",
        check_type="metadata",
        severity="warning",
        violation_hint="Zellen sind hervorgehoben ohne erkennbaren inhaltlichen Grund",
        suggestion_template="Erklaere Hervorhebungen im Kommentar oder entferne sie",
        applies_to=['xlsx'],
    ),
]

# ---------------------------------------------------------------------------
# TECH table rules (machine-checkable)
# ---------------------------------------------------------------------------
TECH_TABLE_RULES: List[IBCSRule] = [
    # TECH-T-01: Cell content types
    IBCSRule(
        id="TECH-T-01.1",
        category="UNIFY",
        name="Text in Wert-Spalte",
        description="Wert-Spalten duerfen nur numerische Werte enthalten",
        check_type="metadata",
        severity="error",
        violation_hint="Textwert in Wertspalte gefunden",
        suggestion_template="Konvertiere Text in numerischen Wert oder entferne ihn aus Wertspalte",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="TECH-T-01.2",
        category="UNIFY",
        name="Gemischte Inhaltstypen in Spalte",
        description="Alle Zellen einer Wert-Spalte sollen denselben Typ haben",
        check_type="metadata",
        severity="error",
        violation_hint="Spalte enthaelt sowohl Text als auch Zahlenwerte",
        suggestion_template="Vereinheitliche Inhaltstypen in Wertspalten",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="TECH-T-01.3",
        category="UNIFY",
        name="Datum als Text formatiert",
        description="Datumsangaben in Zellen muessen als Datum-Typ formatiert sein",
        check_type="metadata",
        severity="warning",
        violation_hint="Datum ist als Text-String statt Datum-Typ in Zelle",
        suggestion_template="Konvertiere Text-Datum in Excel-Datumsformat",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="TECH-T-01.4",
        category="UNIFY",
        name="Formel-Fehler REF oder NAME",
        description="Zellen mit Formel-Fehlern blockieren korrekte Berechnungen",
        check_type="metadata",
        severity="error",
        violation_hint="Zelle enthaelt Formel-Fehler: REF!, NAME!, DIV/0!, WERT!",
        suggestion_template="Behebe den Formel-Fehler in der betroffenen Zelle",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="TECH-T-01.5",
        category="UNIFY",
        name="Leere Formel in Wertzelle",
        description="Leere Formeln (=) ohne Ergebnis sind fehlerhafte Implementierungen",
        check_type="metadata",
        severity="warning",
        violation_hint="Zelle enthaelt leere Formel ohne Wert",
        suggestion_template="Ergaenze Formel oder entferne leere Formelzelle",
        applies_to=['xlsx'],
    ),
    # TECH-T-02: Number formats
    IBCSRule(
        id="TECH-T-02.1",
        category="CONDENSE",
        name="Fehlendes Tausender-Trennzeichen im Format",
        description="Zahlenformat muss Tausender-Trennzeichen enthalten",
        check_type="metadata",
        severity="error",
        violation_hint="Zahlenformat fehlt Tausender-Trennzeichen (#,##0)",
        suggestion_template="Setze Format auf #,##0 oder #,##0.0 fuer Wertspalten",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="TECH-T-02.2",
        category="CONDENSE",
        name="Abweichungsformat ohne Vorzeichen",
        description="Abweichungsformat muss Vorzeichen oder Klammern darstellen",
        check_type="metadata",
        severity="error",
        violation_hint="Abweichungs-Zahlenformat zeigt kein Vorzeichen",
        suggestion_template="Setze Format auf +#,##0;-#,##0 oder #,##0;(#,##0) fuer Abweichungen",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="TECH-T-02.3",
        category="CONDENSE",
        name="Prozent-Spalte ohne Prozent-Format",
        description="Prozentuale Abweichungsspalten brauchen Prozent-Zahlenformat",
        check_type="metadata",
        severity="error",
        violation_hint="Prozent-Spalte hat kein %-Zahlenformat",
        suggestion_template="Setze Format auf 0.0% fuer prozentuale Abweichungsspalten",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="TECH-T-02.4",
        category="CONDENSE",
        name="Inkonsistente Dezimalstellen im Format",
        description="Zahlenformat muss konsistente Dezimalstellen pro Spalte vorgeben",
        check_type="metadata",
        severity="error",
        violation_hint="Verschiedene Zahlenformate mit unterschiedlichen Dezimalstellen in einer Spalte",
        suggestion_template="Vereinheitliche Zahlenformat pro Spalte",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="TECH-T-02.5",
        category="CONDENSE",
        name="Nullwert-Format fehlt",
        description="Zahlenformat soll Nullwerte als Gedankenstrich anzeigen",
        check_type="metadata",
        severity="warning",
        violation_hint="Nullwerte werden als 0 statt als Gedankenstrich angezeigt",
        suggestion_template="Verwende Format #,##0;(#,##0);- fuer Nullwert-Darstellung als Gedankenstrich",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="TECH-T-02.6",
        category="CONDENSE",
        name="Datumsformat nicht standardisiert",
        description="Datumsformat soll einheitlich und klar sein",
        check_type="metadata",
        severity="warning",
        violation_hint="Verschiedene Datumsformate in der Tabelle",
        suggestion_template="Vereinheitliche Datumsformat auf dd.mm.yyyy oder yyyy-mm-dd",
        applies_to=['xlsx'],
    ),
    # TECH-T-03: Font properties
    IBCSRule(
        id="TECH-T-03.1",
        category="UNIFY",
        name="AC-Schrift nicht fett",
        description="AC-Zellen muessen fett formatiert sein",
        check_type="metadata",
        severity="error",
        violation_hint="AC-Zellen haben keine Fettformatierung (bold=False)",
        suggestion_template="Setze Schriftstaerke fett fuer alle AC-Wert-Zellen",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="TECH-T-03.2",
        category="UNIFY",
        name="PY-Schrift nicht kursiv oder grau",
        description="PY-Zellen muessen kursiv oder grau sein",
        check_type="metadata",
        severity="warning",
        violation_hint="PY-Zellen haben keine kursive oder graue Formatierung",
        suggestion_template="Setze PY-Zellen auf kursiv und/oder Schriftfarbe grau",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="TECH-T-03.3",
        category="UNIFY",
        name="PL-Schrift falsch (fett oder schwarz)",
        description="PL-Zellen muessen grau und nicht fett sein",
        check_type="metadata",
        severity="warning",
        violation_hint="PL-Zellen sind fett oder schwarz statt grau",
        suggestion_template="Setze PL-Zellen auf nicht-fett und Schriftfarbe grau",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="TECH-T-03.4",
        category="UNIFY",
        name="Schriftfarbe nicht IBCS-konform",
        description="Schriftfarben muessen IBCS-Farbsemantik folgen",
        check_type="metadata",
        severity="warning",
        violation_hint="Schriftfarben weichen von IBCS-Vorgaben ab",
        suggestion_template="Korrigiere Schriftfarben gemaess IBCS: AC=schwarz, PY=grau, PL=grau",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="TECH-T-03.5",
        category="UNIFY",
        name="Mehr als eine Schriftfamilie",
        description="Tabelle soll nur eine Schriftfamilie verwenden",
        check_type="metadata",
        severity="warning",
        violation_hint="Tabelle enthaelt Zellen mit verschiedenen Schriftfamilien",
        suggestion_template="Vereinheitliche auf eine Schriftfamilie fuer die gesamte Tabelle",
        applies_to=['xlsx'],
    ),
    # TECH-T-04: Background colors by scenario
    IBCSRule(
        id="TECH-T-04.1",
        category="UNIFY",
        name="AC-Hintergrund nicht weiss/hell",
        description="AC-Spalten sollen weissen oder sehr hellen Hintergrund haben (Helligkeit >= 240)",
        check_type="metadata",
        severity="warning",
        violation_hint="AC-Spalten-Hintergrundfarbe ist zu dunkel",
        suggestion_template="Setze AC-Spalten-Hintergrund auf weiss oder sehr helles Grau (RGB >= 240)",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="TECH-T-04.2",
        category="UNIFY",
        name="PY-Hintergrund nicht mittelgrau",
        description="PY-Spalten sollen mittleres Grau als Hintergrund haben (RGB 200-230)",
        check_type="metadata",
        severity="warning",
        violation_hint="PY-Spalten-Hintergrundfarbe liegt nicht im Bereich RGB 200-230",
        suggestion_template="Setze PY-Spalten-Hintergrund auf mittleres Grau (Helligkeit 200-230)",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="TECH-T-04.3",
        category="UNIFY",
        name="PL-Hintergrund nicht hellgrau",
        description="PL-Spalten sollen helles Grau als Hintergrund haben (RGB 230-250)",
        check_type="metadata",
        severity="warning",
        violation_hint="PL-Spalten-Hintergrundfarbe liegt nicht im Bereich RGB 230-250",
        suggestion_template="Setze PL-Spalten-Hintergrund auf helles Grau (Helligkeit 230-250)",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="TECH-T-04.4",
        category="UNIFY",
        name="Abweichungsspalte zu bunte Farbe",
        description="Abweichungsspalten sollen neutrale Hintergrundfarbe haben",
        check_type="metadata",
        severity="warning",
        violation_hint="Abweichungsspalte hat auffaellige Hintergrundfarbe statt Neutral",
        suggestion_template="Setze Abweichungsspalten-Hintergrund auf neutral/weiss",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="TECH-T-04.5",
        category="UNIFY",
        name="Szenario-Farben nicht konsistent",
        description="Szenario-Hintergrundfarben muessen in der gesamten Tabelle konsistent sein",
        check_type="metadata",
        severity="error",
        violation_hint="Szenario-Hintergrundfarben variieren in verschiedenen Tabellenzeilen",
        suggestion_template="Vereinheitliche Szenario-Hintergrundfarben in der gesamten Tabelle",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="TECH-T-04.6",
        category="UNIFY",
        name="FC-Hintergrundfarbe nicht klar",
        description="FC-Spalten sollen eine klar erkennbare Kennzeichnung haben",
        check_type="metadata",
        severity="info",
        violation_hint="FC-Spalten-Hintergrund ist nicht klar von PL oder AC unterscheidbar",
        suggestion_template="Setze FC-Spalten auf eine klar erkennbare Farbe oder Muster",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="TECH-T-04.7",
        category="UNIFY",
        name="Summenzeile ohne Farbe-Hervorhebung",
        description="Summenzeilen sollen durch Hintergrundfarbe hervorgehoben sein",
        check_type="metadata",
        severity="info",
        violation_hint="Summenzeile hat keine Hintergrundfarbe zur Hervorhebung",
        suggestion_template="Setze Summenzeilen auf leicht anderen Hintergrund zur Erkennbarkeit",
        applies_to=['xlsx'],
    ),
    # TECH-T-05: Structure
    IBCSRule(
        id="TECH-T-05.1",
        category="STRUCTURE",
        name="Keine verbundenen Kopfzeilen-Zellen",
        description="Spaltengruppen-Header muessen verbundene Zellen verwenden",
        check_type="metadata",
        severity="warning",
        violation_hint="Keine verbundenen Zellen in Kopfzeilen fuer Spaltengruppen",
        suggestion_template="Verbinde Zellen fuer Spaltengruppen-Header in der Kopfzeile",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="TECH-T-05.2",
        category="STRUCTURE",
        name="Label-Spalte nicht an Position 1",
        description="Zeilenbeschriftungen muessen in Spalte A stehen",
        check_type="metadata",
        severity="error",
        violation_hint="Zeilenbeschriftungs-Spalte ist nicht die erste Spalte",
        suggestion_template="Platziere Label-Spalte an Position 1 (Spalte A)",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="TECH-T-05.3",
        category="STRUCTURE",
        name="Versteckte Zeilen oder Spalten",
        description="Versteckte Zeilen/Spalten koennen wichtige Daten verbergen",
        check_type="metadata",
        severity="warning",
        violation_hint="Tabelle enthaelt versteckte Zeilen oder Spalten",
        suggestion_template="Pruefe und entferne nicht benoetigt versteckte Zeilen/Spalten",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="TECH-T-05.4",
        category="STRUCTURE",
        name="Fehlende Fixierung der Kopfzeile",
        description="Kopfzeilen sollen eingefroren (Freeze Panes) sein",
        check_type="metadata",
        severity="warning",
        violation_hint="Kopfzeile ist nicht eingefroren - scrollt mit Daten weg",
        suggestion_template="Aktiviere Freeze Panes um Kopfzeile sichtbar zu halten",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="TECH-T-05.5",
        category="STRUCTURE",
        name="Fehlender AutoFilter",
        description="IBCS-Tabellen sollen AutoFilter haben fuer interaktive Analyse",
        check_type="metadata",
        severity="info",
        violation_hint="Tabelle hat keinen AutoFilter aktiviert",
        suggestion_template="Aktiviere AutoFilter fuer die Kopfzeile der Tabelle",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="TECH-T-05.6",
        category="STRUCTURE",
        name="Daten ausserhalb Tabellenbereich",
        description="Daten ausserhalb des Haupttabellenbereichs koennen Struktur stoeren",
        check_type="metadata",
        severity="warning",
        violation_hint="Daten oder Text ausserhalb des definierten Tabellenbereichs",
        suggestion_template="Bereinige Daten ausserhalb des Tabellenbereichs",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="TECH-T-05.7",
        category="STRUCTURE",
        name="Zu viele Sheets in einer Datei",
        description="Mehr als 10 relevante Sheets erschweren Navigation",
        check_type="metadata",
        severity="info",
        violation_hint="Excel-Datei hat sehr viele Sheets (mehr als 10)",
        suggestion_template="Konsolidiere Sheets oder teile Datei in thematische Dateien auf",
        applies_to=['xlsx'],
    ),
    # TECH-T-06: Conditional formatting
    IBCSRule(
        id="TECH-T-06.1",
        category="UNIFY",
        name="Abweichungsspalte ohne CF-Regel gruen",
        description="Abweichungsspalten benoetigen CF-Regel gruen fuer positive Werte",
        check_type="metadata",
        severity="error",
        violation_hint="Keine bedingte Formatierung gruen (> 0) in Abweichungsspalte",
        suggestion_template="Fuege CF-Regel hinzu: Wert > 0 = gruene Fuellung",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="TECH-T-06.2",
        category="UNIFY",
        name="Abweichungsspalte ohne CF-Regel rot",
        description="Abweichungsspalten benoetigen CF-Regel rot fuer negative Werte",
        check_type="metadata",
        severity="error",
        violation_hint="Keine bedingte Formatierung rot (< 0) in Abweichungsspalte",
        suggestion_template="Fuege CF-Regel hinzu: Wert < 0 = rote Fuellung",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="TECH-T-06.3",
        category="UNIFY",
        name="CF-Regel ohne Null-Behandlung",
        description="Bedingte Formatierung muss Nullwerte separat behandeln",
        check_type="metadata",
        severity="warning",
        violation_hint="CF-Regeln behandeln Nullwert nicht explizit",
        suggestion_template="Ergaenze CF-Regel: Wert = 0 = neutrale Farbe oder kein Balken",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="TECH-T-06.4",
        category="UNIFY",
        name="CF-Regeln ueberlappend oder widersprueichlich",
        description="CF-Regeln duerfen sich nicht widersprechen",
        check_type="metadata",
        severity="warning",
        violation_hint="Bedingte Formatierungsregeln ueberlappen oder widersprechen sich",
        suggestion_template="Pruefe und bereinige CF-Regeln auf Widersprueche",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="TECH-T-06.5",
        category="UNIFY",
        name="Datenbalken ohne explizite Skalierung",
        description="Datenbalken-CF braucht explizite Min/Max-Werte",
        check_type="metadata",
        severity="error",
        violation_hint="Datenbalken verwendet automatische Skalierung",
        suggestion_template="Setze explizite Min/Max-Werte fuer Datenbalken-Skalierung",
        applies_to=['xlsx'],
    ),
    IBCSRule(
        id="TECH-T-06.6",
        category="UNIFY",
        name="CF-Bereich deckt nicht alle Datenzellen ab",
        description="CF-Regel muss den gesamten Datenbereich abdecken",
        check_type="metadata",
        severity="warning",
        violation_hint="Bedingte Formatierung deckt nicht alle Datenzellen der Spalte ab",
        suggestion_template="Erweitere CF-Bereich auf alle Datenzellen der Abweichungsspalte",
        applies_to=['xlsx'],
    ),
]

# ---------------------------------------------------------------------------
# Combined list of all table rules
# ---------------------------------------------------------------------------
ALL_TABLE_RULES: List[IBCSRule] = (
    UN_TABLE_RULES + EX_TABLE_RULES + CO_TABLE_RULES + CH_TABLE_RULES +
    SI_TABLE_RULES + ST_TABLE_RULES + SA_TABLE_RULES + TECH_TABLE_RULES
)

# Notify ibcs_rules to merge now that this module is fully loaded.
# This handles the case where ibcs_rules was loaded first and its
# _try_merge_table_rules() call found this module still mid-import.
try:
    import sys as _sys
    _ibcs_rules_mod = _sys.modules.get("ibcs_agent.rules.ibcs_rules")
    if _ibcs_rules_mod is not None:
        _fn = getattr(_ibcs_rules_mod, "_try_merge_table_rules", None)
        if _fn is not None:
            _fn()
except Exception:
    pass